version: "1.0"
stages:
  - release
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: release
  build:
    image: klakegg/hugo:0.75.1-ext-alpine
    title: Build Hugo
    commands:
    - git submodule init
    - git submodule update
    - hugo
    - echo $CF_BRANCH
    stage: release
  build_step:
    title: Building container image
    type: build
    image_name: vfarcic/devops-toolkit
    tags:
    - test
    registry: docker-hub
    stage: release
# TODO: Build PR tags (`${{CF_PULL_REQUEST_ID}}`)