version: "1.0"
stages:
  - release
  - deploy
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build:
    image: klakegg/hugo:0.75.1-ext-alpine
    title: Build Hugo
    commands:
    - git submodule init
    - git submodule update
    - hugo
    - echo $CF_PULL_REQUEST_ACTION
    - cf_export REPO_PATH=$PWD
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build_step:
    title: Building container image
    type: build
    image_name: vfarcic/devops-toolkit
    tags:
    - pr-${{CF_PULL_REQUEST_NUMBER}}-${{CF_SHORT_REVISION}}
    registry: docker-hub
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  clone_env_repo:
    title: Cloning preview env. repo
    type: git-clone
    repo: vfarcic/argocd-previews
    stage: deploy
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  define_preview:
    image: alpine
    title: Defining preview environment
    working_directory: "${{clone_env_repo}}" 
    commands:
    - cp $REPO_PATH/preview.yaml helm/templates/pr-$CF_PULL_REQUEST_NUMBER-$CF_REPO_NAME.yaml
    - ls -l helm/templates/
    - cat helm/templates/pr-$CF_PULL_REQUEST_NUMBER-$CF_REPO_NAME.yaml
    stage: deploy
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'

# TODO: Replace CHANGE_TAG, CHANGE_NAME, and CHANGE_HOST
# TODO: Is there a better way to find out whether it is a PR?
# TODO: Split into multiple pipelines?

