version: "1.0"
stages:
  - release
  - deploy
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build:
    image: klakegg/hugo:0.75.1-ext-alpine
    title: Build Hugo
    commands:
    - git submodule init
    - git submodule update
    - hugo
    - export IMAGE_TAG=pr-${{CF_PULL_REQUEST_NUMBER}}-${{CF_SHORT_REVISION}}
    - export REPO_PATH=$PWD
    - cf_export IMAGE_TAG REPO_PATH
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build_step:
    title: Building container image
    type: build
    image_name: vfarcic/devops-toolkit
    tags:
    - ${{IMAGE_TAG}}
    registry: docker-hub
    stage: release
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  clone_env_repo:
    title: Cloning preview env. repo
    type: git-clone
    repo: vfarcic/argocd-previews
    stage: deploy
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  define_preview:
    image: alpine
    title: Defining preview environment
    working_directory: "${{clone_env_repo}}" 
    commands:
    - export APP_ID=pr-$CF_REPO_NAME-$CF_PULL_REQUEST_NUMBER
    - export APP_NAME=$CF_REPO_NAME
    - export APP_HOST=$APP_ID.xip.io
    - apk --no-cache add curl
    - ls -l /usr/local/bin
    - curl -sfL -o /usr/local/bin/kyml https://github.com/frigus02/kyml/releases/download/v20190906/kyml_20190906_linux_amd64
    - chmod +x /usr/local/bin/kyml
    - cat $REPO_PATH/preview.yaml | kyml /usr/local/bin/kyml -e APP_NAME -e IMAGE_TAG -e APP_HOST | tee helm/templates/$APP_ID.yaml
    - cat helm/templates/$APP_ID.yaml
    stage: deploy
    when:
      condition:
        any:
          prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "opened"'
          prSync: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'

# TODO: Replace CHANGE_TAG, CHANGE_NAME, and CHANGE_HOST
# TODO: Is there a better way to find out whether it is a PR?
# TODO: Split into multiple pipelines?
# TODO: When one of the commands fail, the pipeline is still successful

