version: "1.0"
stages:
  - release
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: release
    # when:
    #   condition:
    #     any:
    #       prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build:
    image: klakegg/hugo:0.75.1-ext-alpine
    title: Build Hugo
    commands:
    - git submodule init
    - git submodule update
    - hugo
    - echo $CF_PULL_REQUEST_ACTION
    stage: release
    # when:
    #   condition:
    #     any:
    #       prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'
  build_step:
    title: Building container image
    type: build
    image_name: vfarcic/devops-toolkit
    tags:
    - pr-${{CF_PULL_REQUEST_NUMBER}}-${{CF_SHORT_REVISION}}
    registry: docker-hub
    stage: release
    # when:
    #   condition:
    #     any:
    #       prOpen: '"${{CF_PULL_REQUEST_ACTION}}" == "synchronize"'

# TODO: Is there a better way to find out whether it is a PR?

