version: "3.3"

services:

  main:
    image: vfarcic/devops-toolkit-series
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=www.devopstoolkitseries.com,devopstoolkitseries.com
        - com.df.servicePath=/
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      replicas: 2
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 40M

networks:
  proxy:
    external: true
