{{- if .Values.rollout.deploy }}
---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
  strategy:
    canary:
      canaryService: {{ template "fullname" . }}-canary
      stableService: {{ template "fullname" . }}
      trafficRouting:
        nginx:
          stableIngress: {{ template "fullname" . }}
      steps:
{{ toYaml .Values.rollout.steps | indent 6 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-canary
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
