image:
  tag: 2.6.0
ingress:
  # Choices: none, nginx, gateway
  type: nginx
  host: www.devopstoolkitseries.com
istio:
  enabled: false
resources:
  limits:
   cpu: 15m
   memory: 10Mi
  requests:
   cpu: 5m
   memory: 5Mi
