replicaCount: 1
image:
  repository: vfarcic/devops-toolkit-series
  tag: latest
  pullPolicy: IfNotPresent
knativeDeploy: false
domain: true
ingress:
  host: devopstoolkitseries.com
service:
  name: devops-toolkit
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
