{{- if eq "nginx" .Values.ingress.type }}
{{- $serviceName := include "helm.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: devops-toolkit-ip
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ $serviceName }}
          servicePort: 80
    host: {{ .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: le-{{ $serviceName }}
{{- end -}}