{{- if eq "gateway" .Values.ingress.type }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "helm.fullname" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.ingress.host }}

---
{{- end -}}

{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "helm.fullname" . }}
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - {{ template "helm.fullname" . }}
  http:
  - match:
    route:
    - destination:
        port:
          number: 80
        host: {{ template "helm.fullname" . }}
{{- end -}}
