{{- if .Values.domain }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"  1  
    certmanager.k8s.io/issuer: "letsencrypt-prod"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
    host: www.devopstoolkitseries.com
  tls:
  - hosts:
    - www.devopstoolkitseries.com
    secretName: le-devops-toolkit
{{- end }}